services:
  server:
    image: tankmas2024-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '15001:15001'
    restart: unless-stopped
    volumes:
      - tankmas2024data:/data/:rw

volumes:
  tankmas2024data:
    name: tankmas2024data
